### ISSUE TITLE
Undefined offset 0

### ISSUE THREAD

**Issue by arca223** [WildCodeSchool/parisCode-1017-festival#10]
Hello :)

Petite erreur non catchée lors de l'ajout d'un festival si la ville n'existe pas dans votre base (je suppose)

Steps to reproduce : 

Click "Add Festival"

Fill form with values 

- Title : Rampage.be
- Description : DnB biggest festival in Belgium, Antwerp
- Localisation : Antwerp
- Genre : Drum n Bass
- Amount : 80$
- Starting Date : 2018-03-02
- Ending Date : 2018-03-03

Screenshot profiler : 
<img width="1037" alt="screen shot 2018-02-01 at 14 19 50" src="https://user-images.githubusercontent.com/9930499/35680751-7d028aea-075b-11e8-811e-fec501b0d06d.png">

**Comment by LN-T** [comment]
parameters.yml : missing parameter api_google

**Comment by arca223** [comment]
Ok ça amrche nickel :) Etonnant que j'avais l'erreur pour Antwerp mais pas pour Paris
