### ISSUE TITLE
Love logo (add to whishlist)

### ISSUE THREAD

**Issue by arca223** [WildCodeSchool/parisCode-1017-festival#15]
The Heart logo is present when logged off, but not when logged in ?
Should be the other way because it's a feature only accessible being member OR we could work with session to keep it for the anon. user

To discuss

**Comment by LN-T** [comment]
There were trouble with user/wishlist, I added __construct to get correct association. Now the problem should be fixed (a wishlist is generated with the user creation, so the heart is displayed with the twig).
