### ISSUE TITLE
Wishlist error 500

### ISSUE THREAD

**Issue by arca223** [WildCodeSchool/parisCode-1017-festival#30]
Hello, as we said on the call, please find below the screenshots for the 500
Url of error page : http://127.0.0.1:8000/user/2/wishlist/1/add/festival/3

<img width="1110" alt="screen shot 2018-02-12 at 20 42 15" src="https://user-images.githubusercontent.com/9930499/36116192-c0323f58-1035-11e8-8a18-32c4b5ab0f3c.png">
<img width="1203" alt="screen shot 2018-02-12 at 20 44 27" src="https://user-images.githubusercontent.com/9930499/36116196-c1ce334e-1035-11e8-85de-3e29018923e7.png">
<img width="1196" alt="screen shot 2018-02-12 at 20 44 33" src="https://user-images.githubusercontent.com/9930499/36116199-c3c40160-1035-11e8-898b-282a3d47b6eb.png">
<img width="1034" alt="screen shot 2018-02-12 at 20 44 50" src="https://user-images.githubusercontent.com/9930499/36116200-c5232112-1035-11e8-8c9e-5ed792b206a1.png">

Just entered the basic infos, added a concert btw but it doesn't show on the list when editing (and going to the line up tab)

Not related to this bug but, the location is working (displaying Lyon) and post research, it centers me also on Lyon.
Probably the old data being wrong/bugged so i'll just go back from scratch on the data

**Comment by LN-T** [comment]
I fixed the bug regarding the related festival when adding a concert (it didn't link to the right ID, always the #1"
I couldn't reproduce the rest of the bug (while adding the concert or festival to the wishlist).
