### ISSUE TITLE
Festival popup, all tabs displayed

### ISSUE THREAD

**Issue by arca223** [WildCodeSchool/parisCode-1017-festival#31]
Hello,

All the tabs are displaying on each ones, when opening a festival (popup) on search/discover

<img width="1203" alt="screen shot 2018-02-12 at 20 44 27" src="https://user-images.githubusercontent.com/9930499/36150685-bc9cf056-10c4-11e8-8376-71f2b3a55221.png">
<img width="1196" alt="screen shot 2018-02-12 at 20 44 33" src="https://user-images.githubusercontent.com/9930499/36150686-bcc2b886-10c4-11e8-8e02-eb58019fd818.png">

**Comment by LN-T** [comment]
Jquery reload done !
